### ISSUE TITLE
Filter ein/aus+reset

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_html5#10]
_From @ascheman on September 21, 2015 8:5_

Die gewählten Filter sollten mit einem Schalter ein-/ausgeschaltet werden können, evtl. kombiniert mit einem reset der filter.

~~Evtl. sollte bei einer "leeren" Anzeige ein Hinweis kommen, dass es durch die Filter-Einstellungen keine Anzeige von Talks gibt.~~ (das ist ein anderer Issue: #9)

DIe Nachricht bei leerer Anzeige soll ebenfalls um diesbezügliche Links erweitert werden.

_Copied from original issue: dukecon/dukecon#8_

**Comment by steffchep** [comment]
implemented visuals

**Comment by annam002** [comment]
Saved the "filter active" setting

**Comment by steffchep** [comment]
done
