### ISSUE TITLE
Keycloak issues after move to DOAG accounts

### ISSUE THREAD

**Issue by steffchep** [dukecon/dukecon_html5#102]
When logged in, user name is not shown anymore

**Comment by steffchep** [comment]
In addition, when navigating to a new page on the planner, the lock is open again, and you have to click it to be signed in again - probably something goes wrong with the keycloak-redirect

**_edit_** not always reproducible, appears to happen when Firefox's localStore returns NS_ERROR_FILE_CORRUPTED (which is an FF issue)

**Comment by steffchep** [comment]
https://programm.javaland.eu/auth/realms/javaland/account --> 404

**Comment by steffchep** [comment]
Pushed a workaround - not sure why the accounts are not available

**Comment by ahus1** [comment]
Username is shown when overing over "logged in"
