### ISSUE TITLE
prevent init.json from being called multiple times on first load

### ISSUE THREAD

**Issue by steffchep** [dukecon/dukecon_html5#106]
Problem: login and header widget as well as dukecon and offline modules all call urlprovider.getData. With bad timing this can lead to 4 server requests (at most).

Try something like here, perhaps:

https://stackoverflow.com/questions/29595179/prevent-multiple-ajax-calls-to-the-same-url-within-timeframe

**Comment by ahus1** [comment]
this is fixed in the PWA client.
