### ISSUE TITLE
Client should store image-resources

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_html5#110]
The client loads some image-resources (stream icons, conference logo, sometimes even speaker data) via rest/image-resources.json. The data should be stored into the indexdb and it should be checked every now and then if they have changed as we do with the talk data).

**Comment by ahus1** [comment]
Made a first attempt to fix the HTML so it doesn't load the resource multiple times

**Comment by ahus1** [comment]
Works good enough in old client, works better in new pwa client.
