### ISSUE TITLE
Link to KC account mgmt not effectively switched off

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_html5#111]
In the current DOAG test environment (link via Slack) we see the following behaviour: Though `/rest/keycloak.json` contains the following property `"useAccountManagement":"false"` there is a link to the KeyCloak account management published in the UI:
![dukecon-doag-test-error-account-mgmt-1](https://user-images.githubusercontent.com/456000/29204292-73b3da34-7e76-11e7-851c-44164829da95.PNG)

This should not be visible, nor should be possible to click it and get to the user profile:
![dukecon-doag-test-error-account-mgmt-2](https://user-images.githubusercontent.com/456000/29204335-ac625108-7e76-11e7-8c50-79976e68ec44.PNG)

**Comment by ascheman** [comment]
This was due to a wrong KeyCloak setting (Account management client needs to be disabled). What is the purpose of the `useAccountManagement` property then?

**Comment by steffchep** [comment]
It was introduced to toggle whether or not the app should create a link to keycloak account management. The PWA App no longer uses this.
