### ISSUE TITLE
Logoff should delete all local favorites

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_html5#112]
When a user logs out of DukeCon HTML5 all favorites should be deleted. Otherwise there is always a conflict between local favorites and remote favorites. If a user logs in the remote favorites should override the possible local ones.

Open question: How do we handle local favorites which were set when the user was offline?

**Comment by ahus1** [comment]
Won't fix - with the mechanism in the pwa client (merge only differences) this is no longer necessary.
