### ISSUE TITLE
Scrollposition beibehalten

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_html5#12]
_From @annam002 on September 20, 2015 16:11_

Wenn man in der Talkübersicht gescrollt hat, dann auf die Detailansicht geht, und dann wieder zurück, wäre es wirklich nett, wenn die Scrollposition diesselbe ist wie vorher. Besonders auf dem Handy scrollt man sonst ewig.

_Copied from original issue: dukecon/dukecon#6_

**Comment by steffchep** [comment]
Fixed!
