### ISSUE TITLE
Layout springt wenn Filter ausgewählt werden

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_html5#13]
_From @annam002 on September 18, 2015 13:32_

Das Layout springt bei manchen Filtern, zum Beispiel wenn man "Architektur & Sicherheit" anklickt.

_Copied from original issue: dukecon/dukecon#4_

**Comment by steffchep** [comment]
Lann man feststellen ob das noch passiert? Ich vermute stark, dsas es dann passiert wenn auf einmal der content in die seite passt und daher der Browser die rechte scrollbar ausschaltet

**Comment by steffchep** [comment]
I'm going to close this as I believe that the latest layout changes have eliminated this. 

Reopen if you disagree :)
