### ISSUE TITLE
Systematic explorative browser tests?

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_html5#14]
Should we prepare some systematic explorative browser tests for upcoming releases?
Maybe just a list of _test cases_, e.g., 
- talks/speakers/feedback/impressum
- select/unselect some filters/days
- select some details
- ...

and a matrix of browsers, and OSs, and propably people who could help check it, if we do not have the device, e.g.,

| Browser/OS | Windows (7, 8, 10) | OSX | Linux (Debian, Ubuntu, ...) | Android (4, 5) | iOS (8, 9) / iPhone(5,6/7)+iPad |
| --- | --- | --- | --- | --- | --- |
| Firefox |  |  |  |  |  |
| IE |  |  | :no_entry_sign: |  |  |
| Safari |  |  | :no_entry_sign: |  |  |
| Chrome |  |  |  |  |  |
| Opera? |  |  |  |  |  |
| F.c.Book App | - | - | - |  |  |

Special devices/Owners:
- iXXX: iJUG Office (in fact, the iJUG guys are a hidden apple shop in the end ;-)
- Fedora: @JOpsDev

Then we could just distribute the tests among us, maybe by OS and fill the columns with emoji like 
- :white_check_mark: Test OK
- :x: Test NOT OK
- :no_entry_sign: : Not applicable

**Comment by ahus1** [comment]
closed, unrealistic/won't happen.
