### ISSUE TITLE
Move Menu to header bar and make it more "in your face"

### ISSUE THREAD

**Issue by steffchep** [dukecon/dukecon_html5#19]
Possibly add a thumb-friendly bar at the bottom, where "Impressum" is

**Comment by steffchep** [comment]
Leaving it open to await feedback

**Comment by ascheman** [comment]
## Looks very good, thanks!

Gerd Aschemann - mobil - +49 173 3264070

Am 8. Januar 2016 16:59:38 MEZ, schrieb steffchep notifications@github.com:

**Comment by ascheman** [comment]
It seems to be OK to all?
