### ISSUE TITLE
Impressum: Javaland

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_html5#2]
Please take over the current Impressum from official Javaland site: https://www.javaland.eu/impressum-kontakt/impressum/.

I suspect there will be further requests to take over the complete Javaland footer (with contact form etc.). So we should probably prepare for further alignments or even direct take over of the complete footer with links to the main site pages?

**Comment by steffchep** [comment]
with #4 fixed we have the means to copy their footer. But the space might be better used to add a finger-friendly menu (for smartphone users)

**Comment by steffchep** [comment]
imprint copied; let's create a new ticket for the footer if it comes up!
