### ISSUE TITLE
App slow in Firefox when server is offline due to keycloak.json

### ISSUE THREAD

**Issue by annam002** [dukecon/dukecon_html5#23]
In Firefox, when the app is loaded while the server is offline, it takes really long to load. 
The reason is that the browser tries to retrieve the file keycloak.json from the server, which fails after a long time (in my case, 7.9s). This file should probably be cached.
This does not happen in other browsers (tested in Chrome and Microsoft Edge)

**Comment by ahus1** [comment]
keycloak.json has been added to cache.manifest by @ascheman in 7e612e77e78bb13cb97cd7acaad9c7836a32a5df
I suggest closing this issue.

**Comment by ahus1** [comment]
Submitted pull request #31 to initialize keycloak only when online. Please check if this handles your offline cases successfully. If yes, please merge and maybe also close this ticket. 

I wonder if the login button should be hidden when we are not online?

**Comment by ahus1** [comment]
@annam002 - der PR ist gemerged. Kann das Ticket geschlossen werden?

**Comment by annam002** [comment]
Yep, problem gone.
