### ISSUE TITLE
Enhance publishing loaded favourites

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_html5#30]
Please check out #29, there is an open TODO: dukecloak.js:33 needs to be enhanced to publish the loaded favourites to the view model directly instead of a window reload (would otherwise lead to a infinite loop)

**Comment by annam002** [comment]
Favourites are now overwritten with the favourites from the server when logging in. Should probably be merged instead.

**Comment by annam002** [comment]
Favourites are merged now.

**Comment by annam002** [comment]
Added a check whether something changed before re-filtering the talks after favourites load.

**Comment by annam002** [comment]
Local favourites now overwrite server favourites in the following scenario:
- user logs in and clicks some favourites
- user looses the connection, but keeps changing the favourites
- connection is re-established; the favourites set by the user while offline overwrite the favourites from the server
