### ISSUE TITLE
Setting favorites on Speakers page does not work

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_html5#36]
_From @ascheman on January 8, 2016 16:32_

If a favorite is selected on the speaker overview page it gets lost on the talks page

_Copied from original issue: dukecon/dukecon#24_

**Comment by ahus1** [comment]
Reason was, that no favourites were loaded on the speaker page. When the talk was already selected in the local storage, it showed up as not selected in the frontend. When clicking on the talk on the webpage, the start appeared, but it was deselected in the local storage. when you then switched to the talks page, it was no longer selected. 

Now the favourites are loaded when the page is loaded. then the stars on the page are in sync with the local storage. and no problem occurs. Solved.
