### ISSUE TITLE
Get a fresh small logo from Javaland

### ISSUE THREAD

**Issue by steffchep** [dukecon/dukecon_html5#37]
We are currently using a large Javaland logo that we are shrining via CSS. It doesn't look very nice.

**Comment by ascheman** [comment]
@steffchep can you specify resolution and size?

**Comment by ascheman** [comment]
Addressed to DOAG, we should probably forward the new logo to @chrisdutz for the Flex client too?

**Comment by steffchep** [comment]
The logo on the html page is resized to a height of 35 pixels.

**Comment by ahus1** [comment]
i suppose this is completed?
