### ISSUE TITLE
Give hint on (first) favorite selection to login/sync. service

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_html5#38]
Upon selection of a favorite the user should be advised that he can synchronize between different devices, at least at the first time.

Idea: Use http://usablica.github.io/intro.js/ or similar library.

@steffchep would be great for 1.1 as discussed

**Comment by steffchep** [comment]
Please test. Hint should appear once a day for users that are not logged in (clear cookies to reset)

**Comment by annam002** [comment]
Works, but layout could be improved. Looks a bit cramped now. Maybe some  margin at the bottom and a line between text and ok-button?

**Comment by ascheman** [comment]
Works, please raise a new ticket if you would like to improve the layout ...
