### ISSUE TITLE
Recursive caching causes recursive call of REST service

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_html5#4]
During log file analysis of [the strange Facebook problem](https://github.com/dukecon/dukecon/issues/13) we saw that download of the Application causes multiple calls to the REST interface for talks. Based upon the referrer URLs it seems the following happens:

* / (or index.html) loads cache.manifest and retrieves /rest/talks
* the cache.manifest leads to loading /talks.html, /speakers.html and /impressum.html
* each of the HTML files load the same cache.manifest and even JS libs as index.html
* then the load of /rest/talks etc. is executed again for each HTML file

This ends up in loading the /rest/talks data once for each loaded HTML file causing a certain load and redundant "mass" data sent three or four times to the user.

**Comment by ascheman** [comment]
I think, this is still open (@annam002 could you look into this?)

**Comment by ascheman** [comment]
Deadline 2016-01-17, if not solved postpone to release-1.2

**Comment by annam002** [comment]
I cannot reproduce this. I only get a single call to /rest/talks on load

**Comment by annam002** [comment]
@ascheman Please check if you can still reproduce this and how.

**Comment by ascheman** [comment]
Looks good!
