### ISSUE TITLE
Add Flex-App AppStore-button(s) to imprint

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_html5#40]
As soon as @chrisdutz has published the DukeCon Flex client to the iOS and Android App-Stores there should be an additional button in the imprint (impressum) bar to download/open this.

(Planned as "bugfix" release for 1.1)

**Comment by steffchep** [comment]
Might be a non-issue if we are linking to an external imprint. Place the links somewhere else instead?

**Comment by steffchep** [comment]
Closing; we don't have control over the imprint page anymore.
