### ISSUE TITLE
add cookie disclaimer

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_html5#43]
EU law requires to explain cookie usage to users and to get a consent of the users, cf. https://www.cookielaw.org/.

**Comment by steffchep** [comment]
https://github.com/dukecon/dukecon_html5/commit/e8063b9d054d22124bc2c1d4394913950a867a73 -- added cookie confirmation

**Comment by ascheman** [comment]
Seems to work (have seen the disclaimer very often the last days - every time when deleting the cookies during tests ;-).
