### ISSUE TITLE
Add KeyCloak Profile Link

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_html5#44]
It would be nice, if a logged in user could click on his name in the upper right corner and be connected to the KeyCloak profile login, e.g., https://keycloak.dukecon.org/auth/realms/dukecon-testing/account/.

@srose / @ahus1 : As far as I can see navigating to the link is sufficient when logged in (re-use of tokens), right?

**Comment by srose** [comment]
Yes, this should be fine. Keycloak creates an "Back to application" link. This should work fine (but please verify it)

**Comment by steffchep** [comment]
To make this work without having to change variables, I'll have to somehow extract the realm from the url. Having a look at the options now.

**Comment by steffchep** [comment]
I don't see a "Back to Application" link on the profile page. 

Does this need to be added? If that's not possible, perhaps the profile should be opened in a new tab/window?

**Comment by ascheman** [comment]
The realm can be retrieved from /rest/keycloak.json. If desired we could also add the full URL of the KC user settings URL (or at least the generic part)?

**Comment by steffchep** [comment]
I got the realm figured out :)
