### ISSUE TITLE
Multiple dukecon instances from same domain store into same indexDB

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_html5#45]
We have multiple dukecon instances (latest, testing, testdata, ...) running on the same domain (dev.dukecon.org) which all store into the same indexDB "dukecon".  They should use an instance qualifier, e.g., _$instance to distinguish get an instance private storage, similar to local storage contents.

Is it OK to assign this directly to @annam002?

**Comment by ahus1** [comment]
I see that the etag is saved in the localStorage, the corresponding data is stored in the indexdb. This is asymmetic. I would recommend to store both in the indexdb.

**Comment by ahus1** [comment]
@annam002 @ascheman - this has now been fixed. I also enabled refreshing the contents on the page whenever new data from the server is fetched in the background.
