### ISSUE TITLE
Tabs for Day should be reformatted on mobile

### ISSUE THREAD

**Issue by steffchep** [dukecon/dukecon_html5#46]
They wrap around when there are more than two and it's not so pretty

**Comment by steffchep** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/10571670/12412954/78ac10da-be8b-11e5-8963-8cb0e41591f9.png)

**Comment by ascheman** [comment]
Partly addressed in #41 ;-)

**Comment by ascheman** [comment]
Had the same issue also on small devices with only two days ... 

What about my proposal of "only" current day + left/right arrows?

**Comment by steffchep** [comment]
Thinking (for now) of just shortening the text. But I'll play around with a few options when I get to it

**Comment by steffchep** [comment]
Shortened the weekday when viewing small screens. Don't want to add a whole new library so I hope this is enough. If not, we can also remove the abbreviated weekday to gain more space
