### ISSUE TITLE
ff incognito window only shows spinner after login

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_html5#47]
The spinner (turning wheel cursor) is shown forever when an anonymous/incognito window is used to access dukecon after the keycloak login.

Reproduce by:
- Open incognito window
- Navigate to https://dev.dukecon.org/testing
- Click the lock button to login via keycloak
- Authorize
  The redirect will show the spinner.

You probably will see the following error in the JS console:
`Opening database failed: [object Event] offline.js:368:13 InvalidStateError`

Idea: Check if there is any possibility to test availability of indexedDB etc.

**Comment by annam002** [comment]
This is a "feature" of firefox, see https://bugzilla.mozilla.org/show_bug.cgi?id=1150666
I fixed, but in a really ugly way. Could not find another way. Please test.

**Comment by ascheman** [comment]
Seems to work now in latest FF on OSX and Ubuntu (even with favorite synchronisation - totally "unexpected"). In some cases a second click on the lock symbol is necessary to log in.
