### ISSUE TITLE
Modularize the application

### ISSUE THREAD

**Issue by annam002** [dukecon/dukecon_html5#48]
Dependencies between the js files in the application are a mess. 
Use requirejs to divide the application into proper modules.

**Comment by annam002** [comment]
Involves a lot of changes for all files; will do this after release.

**Comment by dasniko** [comment]
I just started something, what _might_ be possible to support your approach. We discussed yesterday in Skype chat to switch the frontend build process to _Gulp_. There's a `gulp` branch containing the changes.

Additionally to only replacing Maven with Gulp, which wouldn't have an advantage, it is now possible to do a frontend development on `http://localhost:3000`, without requiring to have a local backend server running. There's a proxy middleware plugin, which delegates all rest calls to a somewhere deployed backend server (currently latest ist default). So, no need to run local `file://` protocol anymore and always have a proper server behaviour. The command to run the local server / browser-sync is `gulp watch`.

Furthermore, I'm currently dividing the `.css` files into some kind of base/filter/talks/speaker fragments, adding some _Sass_ magic and building the final css for browser usage during the Gulp build task. With browser-sync, the browser content is automatically refreshed/reloaded when contents change. This leads to a more maintainable approach.

After that, I want to this for the JS files. This could be a good base for modularize the JS things.

_BTW:_ Do you really mean _RequireJS/AMD_? I would prefer _CommonJS_ (which has the `require()` function) with Browserify (or even Webpack), it has a more understandable api/syntax.

**Comment by annam002** [comment]
I wanted to modularize the js next Friday. There is an issue for this on my
name. Already started befor the release but did not merge back yet.
Am 31.01.2016 13:11 schrieb "Niko Köbler" notifications@github.com:

**Comment by dasniko** [comment]
Yes, you and me already commented in your issue... :-)

**Comment by annam002** [comment]
Ok, so, please let me finish this refactoring that I already started before
you change everything.
Am 31.01.2016 14:08 schrieb "Niko Köbler" notifications@github.com:

**Comment by dasniko** [comment]
I didn't change "everything". No JS file relations yet.
Please have a look into the `gulp` branch for what I did, including the readme file!

**Comment by annam002** [comment]
Ok, it sounded like that. ;-) Will check out your changes this afternoon.
Am 31.01.2016 14:18 schrieb "Niko Köbler" notifications@github.com:

**Comment by annam002** [comment]
Modularized the app with requirejs. Still some clean up to do.

**Comment by annam002** [comment]
Left to do: fix the tests

**Comment by ahus1** [comment]
test are now fixed. see 20bd20a78e8261a67c00da02a4cd84883ef47917  and 485ba93b68ed415efd8bdefb3ac123565655cd0f
