### ISSUE TITLE
Environment is shown when logging in with Social Provider

### ISSUE THREAD

**Issue by dasniko** [dukecon/dukecon_html5#50]
When logging in with a Social Provider (first time, when requesting the authorization), the environment is displayed in the name of the application ("(Production)" -> see screenshot)
This is not a real bug, but should be avoided. Users shouldn't be confronted with this information.

GitHub:
<img width="519" alt="bildschirmfoto 2016-01-28 um 15 33 58" src="https://cloud.githubusercontent.com/assets/2075748/12647335/f1629346-c5d4-11e5-9c22-ea5250455f24.png">
Twitter:
<img width="237" alt="bildschirmfoto 2016-01-28 um 15 37 38" src="https://cloud.githubusercontent.com/assets/2075748/12647369/1b88819e-c5d5-11e5-951d-7c6c2b9c6a9b.png">
Didn't see it with Google.

**Comment by steffchep** [comment]
I think this should be in the keycloak project I think - but I don't know how to move it!

**Comment by ascheman** [comment]
The string "(Production)" was set by me in the Github application settings ... I will simply remove it ;-)

**Comment by ascheman** [comment]
Fixed!
