### ISSUE TITLE
Internal Server Error after Logging in with Social Provider

### ISSUE THREAD

**Issue by dasniko** [dukecon/dukecon_html5#51]
I got a "Internal Server Error" Message, when trying to log in with Github and/or Twitter (not tried Google), after redirected back to KC URL https://keycloak.dukecon.org/auth/realms/javaland/login-actions/first-broker-login?code=...
There was only the error message in the browser, no styled error message!

**Comment by steffchep** [comment]
I think this should be in the keycloak project I think - but I don't know how to move it!

**Comment by ahus1** [comment]
Tested again, works.
