### ISSUE TITLE
Keycloak Emails are classified as Spam -> change settings of SMTP server!?

### ISSUE THREAD

**Issue by dasniko** [dukecon/dukecon_html5#52]
All the KC verification emails are gone into my spam folder, so I didn't see them in beneath the 5 mins timeslot (perhaps extend this to 60 mins or so?).

I'm not an expert in configuring SMTP settings, but there are some things like "SPF" record/filter(?) and others, which leads to better results, when set correctly.

If users are not aware of this, they might not be able to use the application.

**Comment by ascheman** [comment]
This issue was moved to dukecon/dukecon_infra#19
