### ISSUE TITLE
Frontend dismisses linefeeds in abstracts

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_html5#57]
The frontend silently drops white space in abstracts, e.g.,
[509505](https://www.doag.org/konferenz/konferenzplaner/konferenzplaner_details.php?locS=0&id=499959&vid=509505) has two paragraphs, which ist not the case in DukeCon: https://dukecon.org/javaland/talk.html#talk?talkId=509505

Data as provided by DOAG back office is delivered with Windows line endings (i.e., '\r\n'). I would like to drop the '\r' completely in the future since it is also contained in some of the title data but without the '\n' (at the end). So a solution for the frontend should be fault tolerant regarding this differences.

@chrisdutz what about the Flex client, should this be solved there also?

**Comment by sippsack** [comment]
dukecon_server now replaces \r\n with \n only
html5 client replaces \n with <br/> in abstract text only

**Comment by sippsack** [comment]
@steffchep, @annam002: can you have a look at my commits. I've replaced \n with <br/>. But I had to disable html encoding to line breaks get rendered correctly. What about cross site scripting?

**Comment by annam002** [comment]
Maybe we can first html-escape the text and then insert the break tags?

**Comment by annam002** [comment]
I escaped potential html characters in the abstract in addition to@sippsack s changes
