### ISSUE TITLE
Synchronization doesn't work as expected

### ISSUE THREAD

**Issue by Jessi626** [dukecon/dukecon_html5#59]
Reproduction:
- I have the website open and am logged in both on my pc and on my phone
- Mark a talk as favourite on the pc
- Refresh the page on my phone
  -> On my phone I can't see the change I just made on my pc

Logging out and in again on my phone didn't help. I had to log out and log in again on my pc, in order to be able to see the changes on my phone.

I would expect to see the changes on my phone after refreshing or at least after logging out and in again.

(Using Firefox 44 and the standard browser on my phone with Android 5.0. Chrome 48 instead of FF behaves the same.)

**Comment by annam002** [comment]
Talked with Jessi. It was expected that synchronisation works differently. Maybe we should look into this.

**Comment by ahus1** [comment]
Syncing of favorites was improved in the PWA; favorites are properly merged and refreshed on reload.
