### ISSUE TITLE
Problems on Fedora with Firefox

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_html5#6]
_From @ascheman on September 25, 2015 12:10_

As reported in #17 (better perform separate tracking) by @JOpsDev

Firefox 40.0.3 on Fedora Linux either tries to load forever if you click on the details page or it shows a details page without any content filled in.

_Copied from original issue: dukecon/dukecon#18_

**Comment by steffchep** [comment]
Which version of Fedora? And does it also occur with the latest Firefox (41.x)?

**Comment by ascheman** [comment]
@JOpsDev: Can you provide the versions of Fedora and Firefox?

**Comment by steffchep** [comment]
Can someone check this again? There have been a lot of changes in the meantime

**Comment by steffchep** [comment]
No feedback, closing.
