### ISSUE TITLE
Multi-Conference: Icons and "conference home" link

### ISSUE THREAD

**Issue by steffchep** [dukecon/dukecon_html5#79]
Conference-Home link title and URL should be part of conference meta-data
If it is not present, don't show a link at all

**Comment by sippsack** [comment]
examples from javaland 2016, urls in dukecon-server:

https://dev.dukecon.org/latest/public/img/499959/conference/logo.png
https://dev.dukecon.org/latest/public/img/499959/languages/1.png
https://dev.dukecon.org/latest/public/img/499959/streams/1.jpg

**Comment by steffchep** [comment]
Removing "urgent" for now - we should look at this soonish after Javaland

**Comment by steffchep** [comment]
Reopening; we still need the track icons
