### ISSUE TITLE
Add tests for Html-App

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_html5#8]
_From @annam002 on September 24, 2015 19:28_

_Copied from original issue: dukecon/dukecon#16_

**Comment by annam002** [comment]
Set up some jasmine tests. Maybe we should add an account here so we can test several browsers automatically: https://saucelabs.com/signup

**Comment by ascheman** [comment]
Could you set up a "dukecon" account? Is it suitable for automated tests driven by Jenkins? If so, please provide me the respective credentials via private messages.

If it's necessary for other people to have such an account to run the test suite, please add a small setup howto to the project (new "docs" folder?).

**Comment by annam002** [comment]
Account was set up; integration with jenkins pending.

**Comment by annam002** [comment]
Added link to test suite to dev-site: https://github.com/dukecon/dukecon_webhome/commit/ec9eded020a5f02d79ae9b2da9d06a4d37557b6b

**Comment by ascheman** [comment]
Tests should be executed during Maven build (or GULP build?) and break the build eventually!

**Comment by ahus1** [comment]
fixed in 20bd20a78e8261a67c00da02a4cd84883ef47917 and 485ba93b68ed415efd8bdefb3ac123565655cd0f
