### ISSUE TITLE
Filters: Improve Experience (was: show only rooms that are used on a given day)

### ISSUE THREAD

**Issue by steffchep** [dukecon/dukecon_html5#84]
For now:
- Fold filters to make them use less space.
- look into keeping the Filter Tab visible all the time on mobile devices (i.e. fixed position)

**Comment by steffchep** [comment]
Alternatively, add folding to filters to save some space

**Comment by ahus1** [comment]
From a UX perspective this doesn't seem possible - how would a user understand that the listed rooms change depending on the selected day?

A similar thing will be implemented by https://github.com/dukecon/dukecon_pwa/issues/60 that will hide categories that are not used by the current conference.
