### ISSUE TITLE
Redesign talk detail page

### ISSUE THREAD

**Issue by steffchep** [dukecon/dukecon_html5#87]
![referentenprofil_monitor_entwurf_1_2](https://cloud.githubusercontent.com/assets/10571670/22595343/684835a2-ea27-11e6-89ba-2db6ff142b24.jpg)

**Comment by steffchep** [comment]
Maybe briefer speaker info?#
What to do with multiple speakers?

**Comment by ascheman** [comment]
Is this an open question? Should we discuss that with DOAG? Should I open a new ticket there?

**Comment by steffchep** [comment]
It might be somehing to ask them, I'm not sure they thought of it when they made the design, and I fear the page will be quite full if there is more than one.

**Comment by steffchep** [comment]
Still open:
- decide if speaker info should be hidden (if there is nothing new to show)
- strategy for mobile (don't generate speaker details in view model if screen size too small)
- re-style talk part as per screenshot (?)

**Comment by steffchep** [comment]
TODO/Story Bugs:
- bug: links in "more talks" all point to current talk -- DONE
- improvement: mobile view with foldable abstract and bio
