### ISSUE TITLE
Link to imprint and other

### ISSUE THREAD

**Issue by steffchep** [dukecon/dukecon_html5#91]
1. See https://redmine.doag.org/issues/4039
2. link to conference home from conference data (if present)

**Comment by steffchep** [comment]
Links are now hardwired for Javaland, so removing the "urgent" for now.

**Comment by steffchep** [comment]
imprint : {
            'de' : 'http://',
            'en' : 'http://'
        },
        termsOfUse : {
            'de' : 'http://',
            'en' : 'http://'
        },
        privacy : {
            'de' : 'http://',
            'en' : 'http://'
        },

**Comment by janwesterkamp** [comment]
server side feature added.
