### ISSUE TITLE
Multiple conferences on same server URL have cache conflict

### ISSUE THREAD

**Issue by ascheman** [dukecon/dukecon_html5#97]
If we have a problem with multiple conferences on the same server URL, e.g.,

* https://programm.doag.org/apex/2017/ and
* https://programm.doag.org/doag/2016/

They both are stored in the same local/indexed db and one cannot switch from one to the other without cleaning up the cache. After cleaning up the cache the other conference can be loaded.

**Comment by steffchep** [comment]
Looks good now!
